"""account_lock_columns

Revision ID: 5ec379faa943
Revises: 0f4f1916613b
Create Date: 2026-05-30 21:46:24.316131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ec379faa943'
down_revision: Union[str, Sequence[str], None] = '0f4f1916613b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('lock_level', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lock_level')
    op.drop_column('users', 'locked_until')
    # ### end Alembic commands ###
