"""add decision and breakdown to login_events

Revision ID: 6a69fcc77033
Revises: f00475d5262d
Create Date: 2026-05-30 23:18:16.922773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a69fcc77033'
down_revision: Union[str, Sequence[str], None] = 'f00475d5262d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_events', sa.Column('decision', sa.String(length=32), nullable=True))
    op.add_column('login_events', sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_login_events_decision'), 'login_events', ['decision'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_login_events_decision'), table_name='login_events')
    op.drop_column('login_events', 'breakdown')
    op.drop_column('login_events', 'decision')
    # ### end Alembic commands ###
